# Configuration de Symfony Messenger
framework:
  messenger:
    # Définition des transports
    transports:
      # Transport pour les messages de géolocalisation
      geolocator_async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          auto_setup: true
          # Configurer la file d'attente
          queue_name: geolocator_queue
          # Configuration des retries
          retry_strategy:
            max_retries: 3
            delay: 1000
            multiplier: 2
            max_delay: 10000

    # Routage des messages vers les transports
    routing:
      # Envoyer les messages de géolocalisation vers le transport geolocator_async
      'GeolocatorBundle\Message\GeolocationMessage': geolocator_async
