controllers:
    resource:
        path: ../../Controller/
        namespace: GeolocatorBundle\Controller
    type: attribute
geolocator:
    resource: '@GeolocatorBundle/Controller/'
    type: attribute
