services:
    # Data collector pour le profiler Symfony
    data_collector.geolocator:
        class: GeolocatorBundle\DataCollector\GeolocatorDataCollector
        arguments:
            $geolocator: '@geolocator.service'
            $enabled: '%geolocator.profiler.enabled%'
        tags:
            - { name: data_collector, template: '@Geolocator/Collector/geolocator.html.twig', id: 'geolocator' }
        public: true

    # Alias du data collector
    geolocator.data_collector:
        alias: data_collector.geolocator

    # Debug controller
    geolocator.controller.debug:
        class: GeolocatorBundle\Controller\GeolocatorDebugController
        arguments:
            $geolocator: '@geolocator.service'
            $enabled: '%geolocator.enabled%'
            $simulate: '%geolocator.simulate%'
            $redirectOnBan: '%geolocator.redirect_on_ban%'
        tags: ['controller.service_arguments']
