services:
    GeolocatorBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Tests}'
    GeolocatorBundle\Provider\:
        resource: '../../Provider'
    GeolocatorBundle\Service\:
        resource: '../../Service'
    GeolocatorBundle\EventListener\:
        resource: '../../EventListener'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    GeolocatorBundle\Export\:
        resource: '../../Export'
    GeolocatorBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']


    # Service to resolve client IP considering trusted proxies
    GeolocatorBundle\Service\IpResolver:
        arguments:
            $trustedProxiesCsv: '%env(TRUSTED_PROXIES)%'


    # PSR-6 Cache for Geolocation
    GeolocatorBundle\Service\GeolocationCache:
        arguments:
            $cachePool: '@cache.app'
            $providerManager: '@GeolocatorBundle\Service\ProviderManager'
            $ttl: '%env(int:GEOLOCATOR_CACHE_TTL)%'


    GeolocatorBundle\Service\BotDetector:
        arguments:
            $botPatterns: '%env(json:BOT_PATTERNS)%'
            $challengeMode: '%env(bool:BOT_CHALLENGE)%'
    GeolocatorBundle\Service\WebhookNotifier:
        arguments:
            $webhooks: '%env(json:WEBHOOK_URLS)%'
