services:
    GeolocatorBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Tests}'
    GeolocatorBundle\Provider\:
        resource: '../../Provider'
    GeolocatorBundle\Service\:
        resource: '../../Service'
    GeolocatorBundle\EventListener\:
        resource: '../../EventSubscriber'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    GeolocatorBundle\Export\:
        resource: '../../Export'
    GeolocatorBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']
    
    GeolocatorBundle\Filter\:
        resource: '../src/Filter'
        tags: ['neox.geofilter.filter']
    
    GeolocatorBundle\Service\WebhookNotifier:
        arguments:
            $httpClient: '@http_client'
            $webhookUrls: '%geolocator.webhooks%'
            $logger: '@logger'
    
    # On regroupe tous les filtres derrière FilterChain
    GeolocatorBundle\Filter\FilterChain :
        arguments :
            $filters : !tagged_iterator neox.geofilter.filter


    GeolocatorBundle\DataCollector\GeolocatorDataCollector:
        arguments:
            $asyncLocator: '@GeolocatorBundle\Service\AsyncGeolocator'
        tags:
            - { name: data_collector, template: '@Geolocator/collector/geolocator.html.twig', id: geolocator }


            
    GeolocatorBundle\EventListener\GeoFilterListener:
        arguments:
            $filters: !tagged_iterator geofilter.filter
            
    # Service to resolve client IP considering trusted proxies
    GeolocatorBundle\Service\IpResolver:
        arguments:
            $trustedProxiesCsv: '%env(TRUSTED_PROXIES)%'


    # PSR-6 Cache for Geolocation
    GeolocatorBundle\Service\GeolocationCache:
        arguments:
            $cachePool: '@cache.app'
            $providerManager: '@GeolocatorBundle\Service\ProviderManager'
            $ttl: '%env(int:GEOLOCATOR_CACHE_TTL)%'


    GeolocatorBundle\Service\BotDetector:
        arguments:
            $botPatterns: '%env(json:BOT_PATTERNS)%'
            $challengeMode: '%env(bool:BOT_CHALLENGE)%'
