services:
    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Configuration automatique des services

    # Définition explicite du service ProviderManager avec ses providers
    GeolocatorBundle\Service\ProviderManager:
        arguments:
            $providers: !tagged_iterator geolocator.provider

    # Configuration explicite pour FilterResult
    GeolocatorBundle\Filter\FilterResult:
        arguments:
            $blocked: false # Valeur par défaut
